package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "server",
    srcs = [
        "configuration.c",
        "configuration.h",
        "server.c",
    ],
    deps = [
        "//workers/common",
    ],
)
